spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.196.127.115:3306/study_springboot?characterEncoding=utf8&useSSL=false
    username: root
    password: Zhou1989!!
    tomcat:
          max-active: 500
          min-idle: 20

#Server
server: 
  port: 9000
  tomcat: 
    uri-encoding: utf-8

#page
pagecount: 10
page: 1
maxpagecount: 1000
#upload path
upload_file_path: /home/program/data/file/
#export path
export_file_path: /home/program/data/export/
